[build]
  functions = "netlify/functions"
  publish = "build"

[dev]
  targetPort = 3000
  command = "npm start"
  
[dev.env]
  PORT = "3000"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
