[build]
  functions = "netlify/functions"
  publish = "build"

[dev]
  targetPort = 3000
  command = "npm start"
  
[dev.env]
  PORT = "3000"
  DISCORD_REDIRECT_URI = "http://localhost:3000"

[context.production.environment]
  DISCORD_REDIRECT_URI = "https://yourdomain.com"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
